name: 'Build'

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
        type: string

# Cancel outdated builds for the same branch
concurrency:
  group: ci-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    # Only run the pull-request build if the pull-request was opened from another repository,
    # since we already run this workflow for the branch the pull request was made from.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Build with Gradle
        run: ./gradlew build

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: build/libs/

      - name: Remove plain variant before publication
        run: rm build/libs/serverpacklocator-*-plain.jar

      - name: Remove utilmod before publication
        run: rm build/libs/serverpacklocator-*-utilmod.jar

      # Auto-Release when pushed to main
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        with:
          tag_name: v${{ inputs.version }}
          files: build/libs/serverpacklocator-*.jar
          make_latest: true
          fail_on_unmatched_files: true
          generate_release_notes: true
